### ISSUE TITLE
How to use try-catch syntax in Android NDK C++ code?

### ISSUE THREAD

**Issue by DJSHICHAOREN** [benjaminwan/OcrLiteAndroidNcnn#1]
![afc8dc57-f8b0-4b96-8bcf-4e1a0e2d7be0](https://user-images.githubusercontent.com/29346132/185896729-3d3209e2-f0b1-404b-b4a3-58ca9768c6f7.jpg)

error: cannot use 'try' with exceptions disabled

somebody said： APP_CPPFLAGS += -fexceptions to Android.mk file.
but now I use CMakeList.txt, There is not Android.mk file in my project.
Thanks.

**Comment by benjaminwan** [comment]
set(CMAKE_CXX_FLAGS "-fexceptions ${CMAKE_CXX_FLAGS}")

**Comment by DJSHICHAOREN** [comment]
> set(CMAKE_CXX_FLAGS "-fexceptions ${CMAKE_CXX_FLAGS}")

Thank your reply！But the problem still exist after I do what you suggest
![image](https://user-images.githubusercontent.com/29346132/187342325-95c5e306-ef4d-428e-b949-1bf9b87a0f44.png)

**Comment by benjaminwan** [comment]
详见README中的编译说明

https://github.com/benjaminwan/OcrLiteAndroidNcnn/blob/master/README.md

注意：解压后还必须修改每个abi目录下的lib/cmake/ncnn/ncnn.cmake，注释掉此行# INTERFACE_COMPILE_OPTIONS "-fno-rtti;-fno-exceptions" 一共有4个文件需要修改，否则会造成编译错误。

ncnn包的cmake配置-fno-exceptions，默认关闭了exception。

**Comment by DJSHICHAOREN** [comment]
> 详见README中的编译说明
> 
> https://github.com/benjaminwan/OcrLiteAndroidNcnn/blob/master/README.md
> 
> 注意：解压后还必须修改每个abi目录下的lib/cmake/ncnn/ncnn.cmake，注释掉此行# INTERFACE_COMPILE_OPTIONS "-fno-rtti;-fno-exceptions" 一共有4个文件需要修改，否则会造成编译错误。
> 
> ncnn包的cmake配置-fno-exceptions，默认关闭了exception。

wow, I succeed ! Very Appreciate！
