### ISSUE TITLE
param is too old, please regenerate!

### ISSUE THREAD

**Issue by DJSHICHAOREN** [benjaminwan/OcrLiteAndroidNcnn#2]
First, I use the ncnn models in https://github.com/ouyanghuiyu/chineseocr_lite/tree/onnx/models_ncnn, but I have an error which is "param is too old, please regenerate!"

![3fb5e73b-42d3-46a1-bc03-463a07b463c7](https://user-images.githubusercontent.com/29346132/187848382-74a7e8f9-bb5c-47fe-b07d-915ac72e8c36.jpg)

For solve this problem, I converter a new  ncnn model use ncnn project and the onnx models in "https://github.com/DayBreak-u/chineseocr_lite/tree/onnx/models".
But then,I got a new error when I compile the project with the new model. The error is "layer Shape not exists or registered".

![472c2a69-c61a-4826-95e7-37547379062b](https://user-images.githubusercontent.com/29346132/187849099-23e54abc-2156-49b1-a246-c6713d130e32.jpg)

Thanks

**Comment by benjaminwan** [comment]
ncnn 20220420，更新后模型支持有变化，需要重新用新版ncnn自带的onnx2ncnn转换模型
一般转换之前，onnx先做simple简化网络，再进行转换

可以直接使用整合好的工程代码
https://github.com/benjaminwan/OcrLiteAndroidNcnn/releases/tag/1.7.0
Project_OcrLiteAndroidNcnn-1.7.0.7z
https://github.com/benjaminwan/OcrLiteAndroidNcnn/releases/download/1.7.0/Project_OcrLiteAndroidNcnn-1.7.0.7z

**Comment by DJSHICHAOREN** [comment]
> ncnn 20220420，更新后模型支持有变化，需要重新用新版ncnn自带的onnx2ncnn转换模型 一般转换之前，onnx先做simple简化网络，再进行转换
> 
> 可以直接使用整合好的工程代码 https://github.com/benjaminwan/OcrLiteAndroidNcnn/releases/tag/1.7.0 Project_OcrLiteAndroidNcnn-1.7.0.7z https://github.com/benjaminwan/OcrLiteAndroidNcnn/releases/download/1.7.0/Project_OcrLiteAndroidNcnn-1.7.0.7z

wow, Thank you very much！
I have used the latest version of  onnx2ncnn to convert the model.But I got the error:"layer Shape not exists or registered"
Is the problem that I do not simplify the onnx net? 
If this is the real problem, is there a tutorial to simplify the onnx net for ncnn?
I'll try your release project, but I want to learn how to simplify the onnx net. 
I am appreciate of you.

**Comment by benjaminwan** [comment]
https://github.com/daquexian/onnx-simplifier

**Comment by DJSHICHAOREN** [comment]
> https://github.com/daquexian/onnx-simplifier

Thank you very much!
