### ISSUE TITLE
没有java代码版本的吗·

### ISSUE THREAD

**Issue by sd3970566** [benjaminwan/OcrLiteAndroidNcnn#3]
chineseocr_lite

**Comment by benjaminwan** [comment]
虽然OcrEngine是用kotlin写的，但调用代码是可以用java的。
主要的难点可能在线程切换，kt用协程，java可以用rxjava来做，或手动写……。
其它没什么了。

**Comment by benjaminwan** [comment]
v1.8.0: 已增加java demo
