### ISSUE TITLE
拉取NCNN安卓端的代码   在adroid studio中打开  报错  Findncnn.cmake

### ISSUE THREAD

**Issue by Cui0526** [benjaminwan/OcrLiteAndroidNcnn#5]
CMake Error at CMakeLists.txt:12 (find_package):
By not providing "Findncnn.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "ncnn", but
CMake did not find one.

**Comment by benjaminwan** [comment]
模型和预编译库很大，没有放进代码仓库里，需要自己手动整合或直接下载整合好的Project，这点Readme里说明了：
整合好源码和依赖库的完整工程项目，可到Q群共享内下载或Release下载，以Project开头的压缩包文件为源码工程，例：Project_OcrLiteAndroidNcnn-版本号.7z
如果想自己折腾，则请继续阅读本说明

**Comment by benjaminwan** [comment]
Release:
https://github.com/benjaminwan/OcrLiteAndroidNcnn/releases/tag/1.8.0

[Project_OcrLiteAndroidNcnn-1.8.0.7z](https://github.com/benjaminwan/OcrLiteAndroidNcnn/releases/download/1.8.0/Project_OcrLiteAndroidNcnn-1.8.0.7z)
