### ISSUE TITLE
SIGBUS 报错,

### ISSUE THREAD

**Issue by rclean** [benjaminwan/OcrLiteAndroidNcnn#6]
安卓端,java+kotlin, ncnn20240410带vulkan的,安卓端在android studio里打的是gpu包 , app/build.gradle 和 Ocr/build.gradle 里的架构都是'arm64-v8a','x86_64'时一切正常,无论是debug打包还是release打包都正常, 

但加上'armeabi-v7a'后,debug打包正常,release打包, 无论是 cpu还是gpu ,会在第二次识别时  (  第一次识别也是什么都没识别出来 ), JNI里的代码 报错SIGBUS ,  ocr的代码混淆 是没有开的  .  CMakeLists.txt里也没有改代码优化等级, 模型是   
ch_PP-OCRv3_det_infer
"ch_ppocr_mobile_v2.0_cls_infer
ch_PP-OCRv3_rec_infer",
"ppocr_keys_v1.txt"

看日志定位了是DbNet.cpp里的

std::vector<TextBox>
DbNet::getTextBoxes(cv::Mat &src, ScaleParam &s, float boxScoreThresh, float boxThresh, float unClipRatio) {
    cv::Mat srcResize;
    cv::resize(src, srcResize, cv::Size(s.dstWidth, s.dstHeight));
    ncnn::Mat input = ncnn::Mat::from_pixels(srcResize.data, ncnn::Mat::PIXEL_RGB,
                                             srcResize.cols, srcResize.rows);

    input.substract_mean_normalize(meanValues, normValues);
    ncnn::Extractor extractor = net.create_extractor();
    extractor.set_num_threads(numThread);
    extractor.input("input", input);
    ncnn::Mat out;
    extractor.extract("output", out);       //报SIGBUS错误
    cv::Mat fMapMat(srcResize.rows, srcResize.cols, CV_32FC1);
    memcpy(fMapMat.data, (float *) out.data, srcResize.rows * srcResize.cols * sizeof(float));
    cv::Mat norfMapMat;
    norfMapMat = fMapMat > boxThresh;

    return findRsBoxes(fMapMat, norfMapMat, s, boxScoreThresh, unClipRatio);
} 
望大大check一下

**Comment by benjaminwan** [comment]
看起来是ncnn的问题，我没有条件试。
你尝试换个ncnn版本试下(老版本也可以试下)
